### ISSUE TITLE
SSDT-PS2M.dsl missing?

### ISSUE THREAD

**Issue by certuna** [kreizlie/HP-EliteBook-840-G4-Hackintosh#2]
Thank you for sharing your work.

You mention a SSDT-PS2M.aml hotpatch in the readme.txt (and it's in the config.plist) but there is no SSDT-PS2M.dsl in the /hotpatch folder. Without it I can't seem to get my trackpad working.

(also, you seem to load VoodooGPIO before VoodooI2CServices, isn't it supposed to be the other way round?)

**Comment by kreizlie** [comment]
Hi my friend, sorry for late response. You can ignore SSDT-PS2M.aml as I use it to disable the trackpad because I suspect a hardware issue with my trackpoint (it cause trackpad stop working on both MacOS and Windows, so I disable it). This laptop's touchpad is SMBUS model, not I2C, so VoodooI2C will not work. You should try VoodooSMBus for Synaptics, I haven't tried it, but I did success to use it on ELAN touchpad (rebuild from source and modify some class names to avoid conflict with VoodoI2C), works really good on Lenovo Yoga 260, I have both touchscreen (I2C) and touchpad (SMBus) with multigestures.

**Comment by kreizlie** [comment]
Hi friend, I've made a release where you can download and test my EFI folder on your machine.

**Comment by certuna** [comment]
Yes I found out in the end that the touchpad is not I2C, I got it working by taking out all the I2C kexts (my Elitebook 840G4 doesn't have a touchscreen) and use the old Rehabman VoodooPS2Controller kexts but those are two years old now so I'll check out the VoodooSMBus, thanks.

**Comment by kreizlie** [comment]
@certuna an update for you, I've made and tested a working multi-gestures trackpad on this laptop, using VoodooRMI.
