### ISSUE TITLE
newer BIOS versions - what causes it to break OpenCore?

### ISSUE THREAD

**Issue by certuna** [kreizlie/HP-EliteBook-840-G4-Hackintosh#3]
As more HP users have found out the recent HP BIOS versions break booting OpenCore (and Clover too btw). Is there any progress anywhere in finding out what exactly causes this?

**Comment by kreizlie** [comment]
Hi friend, do not use HP BIOS 2020 or later, I did some experiments on it, the latest BIOS that works for me is BIOS 2019, in my opinion that BIOS versions are buggy or HP has implement feature that is not supported by OC. Just downgrade your BIOS version.

**Comment by ghost** [comment]
New BIOS causes this in DSDT RTC device:

Device (RTC) { Name (_HID, EisaId ("PNP0B00") /* AT Real-Time Clock */) // _HID: Hardware ID Name (_CRS, ResourceTemplate () // _CRS: Current Resource Settings { IO (Decode16, 0x0070, // Range Minimum 0x0070, // Range Maximum 0x01, // Alignment 0x02, // Length ) IRQNoFlags () {8} }) Method (_STA, 0, NotSerialized) // _STA: Status { If ((STAS == One)) { Return (0x0F) } Else { Return (Zero) } } }

We need to return 0x0F.
This can be fixed by ACPI rename or better way - by SSDT file. You can look at this repository.
kecinzer/hpelitebook850g5-opencore@65338fe

**Comment by kreizlie** [comment]
Great work, thank you @DominikHackintosh
